#!/usr/bin/env bash
#Transfer a file to your server
if [ $# -lt 4 ]; then
    echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4
scp -o StrictHostKeyChecking=no -i $SSH_KEY $FILE $USERNAME@$IP:~/
