#!/usr/bin/env bash
# Install NGINX web server
# Installs nginx server
sudo apt-get update
sudo apt-get install -y nginx

# add to firewall
sudo ufw 'Nginx HTTP'

# Append hello world to file
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

# start nginx server
sudo service nginx start
