#!/usr/bin/env bash
#Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "/server {/a\  \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo nginx -s reload
